In [102]:
%matplotlib inline
import pandas as pd
import numpy as np

In [103]:
data = pd.read_csv('data_for_model.csv')
data.head()

Unnamed: 0  bb_rating  below_b_rating  others_rating  b_rating     tag  \
0           0        0.0             0.0            0.0       0.0  134783   
1           1        0.0             0.0            0.0       0.0   61271   
2           2        0.0             0.0            0.0       0.0   64412   
3           3        0.0             0.0            0.0       0.0  184058   
4           4        0.0             0.0            0.0       0.0  249560   

   a_rating  aaa_rating  aa_rating  bbb_rating  ...  3years_fund_std  \
0       0.0         0.0        0.0         0.0  ...         12.26000   
1       0.0         0.0        0.0         0.0  ...          9.93000   
2       0.0         0.0        0.0         0.0  ...          8.36000   
3       0.0         0.0        0.0         0.0  ...         16.29992   
4       0.0         0.0        0.0         0.0  ...          8.24000   

   3_years_alpha_category  3_years_return_mean_annual_category  \
0                    0.01                                 0.01   
1                    0.01                                 0.01   
2                   -0.02                                 0.01   
3                   -0.01                                 0.01   
4                    0.01                                 0.01   

   5yrs_sharpe_ratio_category  5_years_return_mean_annual_category  \
0                        0.01                                 0.01   
1                        0.01                                 0.01   
2                        0.01                                 0.01   
3                        0.01                                 0.01   
4                        0.01                                 0.01   

   5yrs_treynor_ratio_category  5_years_return_fund  5_years_alpha_category  \
0                         0.10                11.71                   -0.00   
1                         0.10                12.78                   -0.00   
2                         0.07                 7.25                   -0.03   
3                         0.04                 0.00                   -0.01   
4                         0.04                 5.65                   -0.00   

   5_years_beta_category  5_years_return_category  
0                   0.01                    11.26  
1                   0.01                    11.26  
2                   0.01                     7.20  
3                   0.01                     5.95  
4                   0.01                     5.89  

[5 rows x 71 columns]

In [104]:
data.drop(columns=['Unnamed: 0'],inplace=True)

In [105]:
data.shape

(19862, 70)

In [25]:
data.columns

Index(['bb_rating', 'below_b_rating', 'others_rating', 'b_rating', 'tag',
       'a_rating', 'aaa_rating', 'aa_rating', 'bbb_rating',
       'portfolio_financial_services', 'portfolio_industrials_allocation',
       'portfolio_tech_allocation', 'portfolio_materials_basic_allocation',
       'portfolio_energy_allocation', 'portfolio_consumer_defence_allocation',
       'portfolio_healthcare_allocation', 'portfolio_property_allocation',
       'portfolio_utils_allocation', 'portfolio_cyclical_consumer_allocation',
       'fund_id', 'total_assets', 'yield', 'greatstone_rating', 'return_ytd',
       'fund_ratio_net_annual_expense', 'pb_ratio', 'ps_ratio', 'mmc',
       'pc_ratio', 'pe_ratio', 'years_up', '2018_return_category',
       'category_return_1year', 'cash_percent_of_portfolio', 'years_down',
       'category_return_1month', '2017_category_return', '1_year_return_fund',
       'portfolio_convertable', '3_months_return_category', 'portfolio_others',
       'fund_return_3years', '20

In [20]:
data.isnull().sum()

bb_rating                                 0
below_b_rating                            0
others_rating                             0
b_rating                                  0
a_rating                                  0
aaa_rating                                0
aa_rating                                 0
bbb_rating                                0
portfolio_financial_services              0
portfolio_industrials_allocation          0
portfolio_tech_allocation                 0
portfolio_materials_basic_allocation      0
portfolio_energy_allocation               0
portfolio_consumer_defence_allocation     0
portfolio_healthcare_allocation           0
portfolio_property_allocation             0
portfolio_utils_allocation                0
portfolio_cyclical_consumer_allocation    0
total_assets                              0
yield                                     0
greatstone_rating                         0
return_ytd                                0
fund_ratio_net_annual_expense   

In [6]:
data.dtypes

bb_rating                                 float64
below_b_rating                            float64
others_rating                             float64
b_rating                                  float64
tag                                         int64
a_rating                                  float64
aaa_rating                                float64
aa_rating                                 float64
bbb_rating                                float64
portfolio_financial_services              float64
portfolio_industrials_allocation          float64
portfolio_tech_allocation                 float64
portfolio_materials_basic_allocation      float64
portfolio_energy_allocation               float64
portfolio_consumer_defence_allocation     float64
portfolio_healthcare_allocation           float64
portfolio_property_allocation             float64
portfolio_utils_allocation                float64
portfolio_cyclical_consumer_allocation    float64
fund_id                                    object


In [106]:
#data['tag']=data['tag'].astype('object')
data['greatstone_rating']=data['greatstone_rating'].astype('category')

In [15]:
df_x =data[data.select_dtypes(include=['object']).columns]
df_x.columns

Index(['tag', 'fund_id'], dtype='object')

In [27]:
data['tag'].head()

0    134783
1     61271
2     64412
3    184058
4    249560
Name: tag, dtype: int64

In [107]:
from sklearn.model_selection import train_test_split
data.drop(columns=['tag','fund_id'],inplace=True)

X = np.array(data.drop(columns='greatstone_rating'))
y = np.array(data['greatstone_rating'])

In [116]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=10)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(13903, 67)
(5959, 67)
(13903,)
(5959,)


In [30]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = 'entropy' )
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [31]:
y_predict_test = model.predict(X_test)
model_score_test = model.score(X_test,y_test)
from sklearn import metrics
print(model_score_test)
print(metrics.confusion_matrix(y_test,y_predict_test))
print(metrics.classification_report(y_test,y_predict_test))

0.7044806175532807
[[ 400    3    8    1    1    0]
 [   6  238  123   21    6    1]
 [   0  112  853  259   41   11]
 [   3   20  225 1432  289   26]
 [   2    7   29  284  943  142]
 [   1    0    6   21  113  332]]
              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97       413
         1.0       0.63      0.60      0.61       395
         2.0       0.69      0.67      0.68      1276
         3.0       0.71      0.72      0.71      1995
         4.0       0.68      0.67      0.67      1407
         5.0       0.65      0.70      0.67       473

    accuracy                           0.70      5959
   macro avg       0.72      0.72      0.72      5959
weighted avg       0.70      0.70      0.70      5959



In [32]:
data_1 =data.drop(columns='greatstone_rating')
pd.DataFrame(model.feature_importances_,columns=['Imp'],index =data_1.columns)

Imp
bb_rating                               0.004836
below_b_rating                          0.002998
others_rating                           0.003268
b_rating                                0.001656
a_rating                                0.004457
aaa_rating                              0.003280
aa_rating                               0.004994
bbb_rating                              0.004450
portfolio_financial_services            0.006119
portfolio_industrials_allocation        0.005751
portfolio_tech_allocation               0.006140
portfolio_materials_basic_allocation    0.007762
portfolio_energy_allocation             0.007293
portfolio_consumer_defence_allocation   0.006104
portfolio_healthcare_allocation         0.006556
portfolio_property_allocation           0.005366
portfolio_utils_allocation              0.005536
portfolio_cyclical_consumer_allocation  0.004651
total_assets                            0.024151
yield                                   0.019611
return_ytd                              0.012373
fund_ratio_net_annual_expense           0.024847
pb_ratio                                0.002740
ps_ratio                                0.005909
mmc                                     0.005039
pc_ratio                                0.005999
pe_ratio                                0.009428
years_up                                0.016601
2018_return_category                    0.005260
category_return_1year                   0.010872
...                                          ...
portfolio_others                        0.006712
fund_return_3years                      0.026057
2018_return_fund                        0.018062
category_ratio_net_annual_expense       0.008600
1_month_fund_return                     0.014891
bond_percentage_of_porfolio             0.005696
portfolio_preferred                     0.002669
10years_category_r_squared              0.001782
10yrs_sharpe_ratio_category             0.000186
10_years_return_mean_annual_category    0.000000
10yrs_treynor_ratio_category            0.007144
10_years_return_fund                    0.050451
10_years_alpha_category                 0.005041
10years_category_std                    0.000818
3yrs_treynor_ratio_fund                 0.030830
3_years_alpha_fund                      0.126343
3yrs_sharpe_ratio_fund                  0.026397
3yrs_treynor_ratio_category             0.010462
fund_beta_3years                        0.154743
3years_fund_r_squared                   0.017472
3years_fund_std                         0.013555
3_years_alpha_category                  0.026191
3_years_return_mean_annual_category     0.000330
5yrs_sharpe_ratio_category              0.000101
5_years_return_mean_annual_category     0.000000
5yrs_treynor_ratio_category             0.005526
5_years_return_fund                     0.109132
5_years_alpha_category                  0.003279
5_years_beta_category                   0.000112
5_years_return_category                 0.036310

[67 rows x 1 columns]

In [113]:
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start = 20, stop = 500, num = 10)]
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]
random_grid = {'n_estimators': n_estimators,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [114]:
rfcl = RandomForestClassifier()

In [115]:
from sklearn.model_selection import RandomizedSearchCV
rf_random = RandomizedSearchCV(estimator = rfcl, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42)

In [117]:
rf_random.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=1, max_depth=None, bootstrap=False 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  n_estimators=500, min_samples_split=2, min_samples_leaf=1, max_depth=None, bootstrap=False, total=  39.2s
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=1, max_depth=None, bootstrap=False 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   39.1s remaining:    0.0s


[CV]  n_estimators=500, min_samples_split=2, min_samples_leaf=1, max_depth=None, bootstrap=False, total=  35.2s
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=1, max_depth=None, bootstrap=False 
[CV]  n_estimators=500, min_samples_split=2, min_samples_leaf=1, max_depth=None, bootstrap=False, total=  34.7s
[CV] n_estimators=446, min_samples_split=2, min_samples_leaf=2, max_depth=80, bootstrap=True 
[CV]  n_estimators=446, min_samples_split=2, min_samples_leaf=2, max_depth=80, bootstrap=True, total=  23.4s
[CV] n_estimators=446, min_samples_split=2, min_samples_leaf=2, max_depth=80, bootstrap=True 
[CV]  n_estimators=446, min_samples_split=2, min_samples_leaf=2, max_depth=80, bootstrap=True, total=  21.1s
[CV] n_estimators=446, min_samples_split=2, min_samples_leaf=2, max_depth=80, bootstrap=True 
[CV]  n_estimators=446, min_samples_split=2, min_samples_leaf=2, max_depth=80, bootstrap=True, total=  22.0s
[CV] n_estimators=180, min_samples_split=2, min_samples_leaf=1, max_de

[CV]  n_estimators=233, min_samples_split=10, min_samples_leaf=4, max_depth=10, bootstrap=False, total=  10.9s
[CV] n_estimators=393, min_samples_split=10, min_samples_leaf=1, max_depth=70, bootstrap=True 
[CV]  n_estimators=393, min_samples_split=10, min_samples_leaf=1, max_depth=70, bootstrap=True, total=  16.1s
[CV] n_estimators=393, min_samples_split=10, min_samples_leaf=1, max_depth=70, bootstrap=True 
[CV]  n_estimators=393, min_samples_split=10, min_samples_leaf=1, max_depth=70, bootstrap=True, total=  18.0s
[CV] n_estimators=393, min_samples_split=10, min_samples_leaf=1, max_depth=70, bootstrap=True 
[CV]  n_estimators=393, min_samples_split=10, min_samples_leaf=1, max_depth=70, bootstrap=True, total=  17.6s
[CV] n_estimators=286, min_samples_split=5, min_samples_leaf=2, max_depth=20, bootstrap=True 
[CV]  n_estimators=286, min_samples_split=5, min_samples_leaf=2, max_depth=20, bootstrap=True, total=  12.1s
[CV] n_estimators=286, min_samples_split=5, min_samples_leaf=2, max_dep

[CV]  n_estimators=73, min_samples_split=5, min_samples_leaf=4, max_depth=30, bootstrap=True, total=   2.8s
[CV] n_estimators=73, min_samples_split=5, min_samples_leaf=4, max_depth=30, bootstrap=True 
[CV]  n_estimators=73, min_samples_split=5, min_samples_leaf=4, max_depth=30, bootstrap=True, total=   2.6s
[CV] n_estimators=73, min_samples_split=5, min_samples_leaf=4, max_depth=30, bootstrap=True 
[CV]  n_estimators=73, min_samples_split=5, min_samples_leaf=4, max_depth=30, bootstrap=True, total=   2.8s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=4, max_depth=40, bootstrap=False 
[CV]  n_estimators=20, min_samples_split=5, min_samples_leaf=4, max_depth=40, bootstrap=False, total=   1.1s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=4, max_depth=40, bootstrap=False 
[CV]  n_estimators=20, min_samples_split=5, min_samples_leaf=4, max_depth=40, bootstrap=False, total=   1.2s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=4, max_depth=40, bootstr

[CV]  n_estimators=73, min_samples_split=5, min_samples_leaf=4, max_depth=30, bootstrap=False, total=   3.9s
[CV] n_estimators=500, min_samples_split=10, min_samples_leaf=1, max_depth=50, bootstrap=False 
[CV]  n_estimators=500, min_samples_split=10, min_samples_leaf=1, max_depth=50, bootstrap=False, total=  27.9s
[CV] n_estimators=500, min_samples_split=10, min_samples_leaf=1, max_depth=50, bootstrap=False 
[CV]  n_estimators=500, min_samples_split=10, min_samples_leaf=1, max_depth=50, bootstrap=False, total=  28.7s
[CV] n_estimators=500, min_samples_split=10, min_samples_leaf=1, max_depth=50, bootstrap=False 
[CV]  n_estimators=500, min_samples_split=10, min_samples_leaf=1, max_depth=50, bootstrap=False, total=  28.5s
[CV] n_estimators=286, min_samples_split=5, min_samples_leaf=2, max_depth=100, bootstrap=False 
[CV]  n_estimators=286, min_samples_split=5, min_samples_leaf=2, max_depth=100, bootstrap=False, total=  16.6s
[CV] n_estimators=286, min_samples_split=5, min_samples_leaf=2,

[CV]  n_estimators=233, min_samples_split=5, min_samples_leaf=2, max_depth=20, bootstrap=True, total=   8.8s
[CV] n_estimators=233, min_samples_split=5, min_samples_leaf=2, max_depth=20, bootstrap=True 
[CV]  n_estimators=233, min_samples_split=5, min_samples_leaf=2, max_depth=20, bootstrap=True, total=   8.8s
[CV] n_estimators=233, min_samples_split=5, min_samples_leaf=2, max_depth=20, bootstrap=True 
[CV]  n_estimators=233, min_samples_split=5, min_samples_leaf=2, max_depth=20, bootstrap=True, total=   8.8s
[CV] n_estimators=340, min_samples_split=10, min_samples_leaf=4, max_depth=60, bootstrap=False 
[CV]  n_estimators=340, min_samples_split=10, min_samples_leaf=4, max_depth=60, bootstrap=False, total=  18.3s
[CV] n_estimators=340, min_samples_split=10, min_samples_leaf=4, max_depth=60, bootstrap=False 
[CV]  n_estimators=340, min_samples_split=10, min_samples_leaf=4, max_depth=60, bootstrap=False, total=  23.1s
[CV] n_estimators=340, min_samples_split=10, min_samples_leaf=4, max_de

[CV]  n_estimators=340, min_samples_split=2, min_samples_leaf=4, max_depth=50, bootstrap=False, total=  19.4s
[CV] n_estimators=446, min_samples_split=2, min_samples_leaf=4, max_depth=90, bootstrap=False 
[CV]  n_estimators=446, min_samples_split=2, min_samples_leaf=4, max_depth=90, bootstrap=False, total=  28.6s
[CV] n_estimators=446, min_samples_split=2, min_samples_leaf=4, max_depth=90, bootstrap=False 
[CV]  n_estimators=446, min_samples_split=2, min_samples_leaf=4, max_depth=90, bootstrap=False, total=  24.6s
[CV] n_estimators=446, min_samples_split=2, min_samples_leaf=4, max_depth=90, bootstrap=False 
[CV]  n_estimators=446, min_samples_split=2, min_samples_leaf=4, max_depth=90, bootstrap=False, total=  24.4s
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=1, max_depth=100, bootstrap=True 
[CV]  n_estimators=500, min_samples_split=2, min_samples_leaf=1, max_depth=100, bootstrap=True, total=  20.2s
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=1, max_de

[CV]  n_estimators=180, min_samples_split=10, min_samples_leaf=1, max_depth=None, bootstrap=False, total=  12.6s
[CV] n_estimators=180, min_samples_split=10, min_samples_leaf=1, max_depth=None, bootstrap=False 
[CV]  n_estimators=180, min_samples_split=10, min_samples_leaf=1, max_depth=None, bootstrap=False, total=  11.2s
[CV] n_estimators=180, min_samples_split=2, min_samples_leaf=4, max_depth=80, bootstrap=True 
[CV]  n_estimators=180, min_samples_split=2, min_samples_leaf=4, max_depth=80, bootstrap=True, total=   6.4s
[CV] n_estimators=180, min_samples_split=2, min_samples_leaf=4, max_depth=80, bootstrap=True 
[CV]  n_estimators=180, min_samples_split=2, min_samples_leaf=4, max_depth=80, bootstrap=True, total=   6.7s
[CV] n_estimators=180, min_samples_split=2, min_samples_leaf=4, max_depth=80, bootstrap=True 
[CV]  n_estimators=180, min_samples_split=2, min_samples_leaf=4, max_depth=80, bootstrap=True, total=   8.0s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=4, max_

[CV]  n_estimators=20, min_samples_split=10, min_samples_leaf=1, max_depth=80, bootstrap=False, total=   1.2s
[CV] n_estimators=20, min_samples_split=10, min_samples_leaf=1, max_depth=80, bootstrap=False 
[CV]  n_estimators=20, min_samples_split=10, min_samples_leaf=1, max_depth=80, bootstrap=False, total=   1.1s
[CV] n_estimators=20, min_samples_split=10, min_samples_leaf=1, max_depth=80, bootstrap=False 
[CV]  n_estimators=20, min_samples_split=10, min_samples_leaf=1, max_depth=80, bootstrap=False, total=   1.2s
[CV] n_estimators=340, min_samples_split=5, min_samples_leaf=1, max_depth=30, bootstrap=True 
[CV]  n_estimators=340, min_samples_split=5, min_samples_leaf=1, max_depth=30, bootstrap=True, total=  13.3s
[CV] n_estimators=340, min_samples_split=5, min_samples_leaf=1, max_depth=30, bootstrap=True 
[CV]  n_estimators=340, min_samples_split=5, min_samples_leaf=1, max_depth=30, bootstrap=True, total=  18.0s
[CV] n_estimators=340, min_samples_split=5, min_samples_leaf=1, max_depth=

[Parallel(n_jobs=1)]: Done 300 out of 300 | elapsed: 64.9min finished


RandomizedSearchCV(cv=3, error_score='raise-deprecating',
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    n_estimators='warn',
                                                    n_jobs=None

In [118]:
rf_random.best_params_

{'n_estimators': 393,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_depth': 80,
 'bootstrap': False}

In [119]:
from sklearn.ensemble import RandomForestClassifier
rfcl = RandomForestClassifier(n_estimators = 393,min_samples_split=2,min_samples_leaf=2,max_depth=80,bootstrap= False)
rfcl = rfcl.fit(X_train, y_train)

In [120]:
y_predict_test = rfcl.predict(X_test)
model_score_test = rfcl.score(X_test,y_test)
print(model_score_test)
print(metrics.confusion_matrix(y_test,y_predict_test))
print(metrics.classification_report(y_test,y_predict_test))

0.7737875482463501
[[ 404    2    2    3    0    2]
 [   1  241  134   19    0    0]
 [   1   41  975  248   11    0]
 [   1    0  175 1626  186    7]
 [   0    0   11  285 1043   68]
 [   0    0    1    9  141  322]]
              precision    recall  f1-score   support

         0.0       0.99      0.98      0.99       413
         1.0       0.85      0.61      0.71       395
         2.0       0.75      0.76      0.76      1276
         3.0       0.74      0.82      0.78      1995
         4.0       0.76      0.74      0.75      1407
         5.0       0.81      0.68      0.74       473

    accuracy                           0.77      5959
   macro avg       0.82      0.76      0.79      5959
weighted avg       0.78      0.77      0.77      5959



In [82]:
data_test = pd.read_csv('test1.csv')
data_test.head()

Unnamed: 0  bb_rating  us_govt_bond_rating  below_b_rating  others_rating  \
0           0       0.00                  0.0             0.0           0.00   
1           1       0.00                  0.0             0.0           0.00   
2           2       0.00                  0.0             0.0           0.00   
3           3       5.33                  0.0             0.0           0.04   
4           4       0.80                  0.0             0.0          22.80   

   b_rating     tag  a_rating  aaa_rating  aa_rating  ...  \
0      0.00   67922      0.00        0.00       0.00  ...   
1      0.00  138257      0.00        0.00       0.00  ...   
2      0.00  191978      0.00        0.00       0.00  ...   
3      0.98  105506     35.19        2.79       5.78  ...   
4      0.90   58517     27.00        7.20      22.10  ...   

   3_years_return_category  category_r_squared_5years  \
0                     7.36                       0.51   
1                    10.01                       0.86   
2                    15.88                       0.65   
3                     9.94                       0.95   
4                     1.11                       0.66   

   5yrs_sharpe_ratio_category  5_years_return_mean_annual_category  \
0                        0.00                                 0.00   
1                        0.01                                 0.01   
2                        0.01                                 0.01   
3                        0.01                                 0.01   
4                        0.00                                 0.00   

   5yrs_treynor_ratio_category  5_years_return_fund  5_years_alpha_category  \
0                        -0.04                 0.00                   -0.11   
1                         0.07                 0.00                   -0.03   
2                         0.06                 6.54                   -0.03   
3                         0.04                 7.10                   -0.01   
4                         0.04                 1.09                   -0.01   

   5_years_beta_category  5years_category_std  5_years_return_category  
0                   0.01                 0.20                    -4.25  
1                   0.01                 0.11                     7.20  
2                   0.01                 0.17                     8.45  
3                   0.01                 0.10                     6.41  
4                   0.00                 0.01                     1.14  

[5 rows x 94 columns]

In [83]:
data_test.drop(columns=['Unnamed: 0'],inplace=True)

In [39]:
data_1.columns

Index(['bb_rating', 'below_b_rating', 'others_rating', 'b_rating', 'a_rating',
       'aaa_rating', 'aa_rating', 'bbb_rating', 'portfolio_financial_services',
       'portfolio_industrials_allocation', 'portfolio_tech_allocation',
       'portfolio_materials_basic_allocation', 'portfolio_energy_allocation',
       'portfolio_consumer_defence_allocation',
       'portfolio_healthcare_allocation', 'portfolio_property_allocation',
       'portfolio_utils_allocation', 'portfolio_cyclical_consumer_allocation',
       'total_assets', 'yield', 'return_ytd', 'fund_ratio_net_annual_expense',
       'pb_ratio', 'ps_ratio', 'mmc', 'pc_ratio', 'pe_ratio', 'years_up',
       '2018_return_category', 'category_return_1year',
       'cash_percent_of_portfolio', 'years_down', 'category_return_1month',
       '2017_category_return', '1_year_return_fund', 'portfolio_convertable',
       '3_months_return_category', 'portfolio_others', 'fund_return_3years',
       '2018_return_fund', 'category_ratio_net_an

In [84]:
data_test_1=data_test[['bb_rating', 'below_b_rating', 'others_rating', 'b_rating', 'a_rating',
       'aaa_rating', 'aa_rating', 'bbb_rating', 'portfolio_financial_services',
       'portfolio_industrials_allocation', 'portfolio_tech_allocation',
       'portfolio_materials_basic_allocation', 'portfolio_energy_allocation',
       'portfolio_consumer_defence_allocation',
       'portfolio_healthcare_allocation', 'portfolio_property_allocation',
       'portfolio_utils_allocation', 'portfolio_cyclical_consumer_allocation',
       'total_assets', 'yield', 'return_ytd', 'fund_ratio_net_annual_expense',
       'pb_ratio', 'ps_ratio', 'mmc', 'pc_ratio', 'pe_ratio', 'years_up',
       '2018_return_category', 'category_return_1year',
       'cash_percent_of_portfolio', 'years_down', 'category_return_1month',
       '2017_category_return', '1_year_return_fund', 'portfolio_convertable',
       '3_months_return_category', 'portfolio_others', 'fund_return_3years',
       '2018_return_fund', 'category_ratio_net_annual_expense',
       '1_month_fund_return', 'bond_percentage_of_porfolio',
       'portfolio_preferred', '10years_category_r_squared',
       '10yrs_sharpe_ratio_category', '10_years_return_mean_annual_category',
       '10yrs_treynor_ratio_category', '10_years_return_fund',
       '10_years_alpha_category', '10years_category_std',
       '3yrs_treynor_ratio_fund', '3_years_alpha_fund',
       '3yrs_sharpe_ratio_fund', '3yrs_treynor_ratio_category',
       'fund_beta_3years', '3years_fund_r_squared', '3years_fund_std',
       '3_years_alpha_category', '3_years_return_mean_annual_category',
       '5yrs_sharpe_ratio_category', '5_years_return_mean_annual_category',
       '5yrs_treynor_ratio_category', '5_years_return_fund',
       '5_years_alpha_category', '5_years_beta_category',
       '5_years_return_category']]

In [85]:
data_test_1.shape

(5000, 67)

In [64]:
data_test.isnull().sum()

bb_rating                                  19
below_b_rating                             19
others_rating                              19
b_rating                                   19
a_rating                                   19
aaa_rating                                 19
aa_rating                                  19
bbb_rating                                 19
portfolio_financial_services               19
portfolio_industrials_allocation           19
portfolio_tech_allocation                  19
portfolio_materials_basic_allocation       19
portfolio_energy_allocation                19
portfolio_consumer_defence_allocation      19
portfolio_healthcare_allocation            19
portfolio_property_allocation              19
portfolio_utils_allocation                 19
portfolio_cyclical_consumer_allocation     19
total_assets                                0
yield                                       0
return_ytd                                  0
fund_ratio_net_annual_expense     

In [86]:
import re
data_test_1['mmc']=data_test_1['mmc'].apply(lambda x: re.sub(',','',str(x)))
data_test_1['pc_ratio']=data_test_1['pc_ratio'].apply(lambda x: re.sub(',','',str(x)))
data_test_1['pe_ratio']=data_test_1['pe_ratio'].apply(lambda x: re.sub(',','',str(x)))
data_test_1['3yrs_treynor_ratio_fund']=data_test_1['3yrs_treynor_ratio_fund'].apply(lambda x: re.sub(',','',str(x)))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in t

In [87]:
data_test_1['mmc']=data_test_1['mmc'].astype('float64')
data_test_1['pc_ratio']=data_test_1['pc_ratio'].astype('float64')
data_test_1['pe_ratio']=data_test_1['pe_ratio'].astype('float64')
data_test_1['3yrs_treynor_ratio_fund']=data_test_1['3yrs_treynor_ratio_fund'].astype('float64')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.

In [88]:
def fill_mis(df):
    total = df.isnull().sum().sort_values(ascending=False)
    mis_data=pd.DataFrame(total).reset_index()
    mis_data.columns=['Features','Total']
    x=np.array(mis_data['Features'][mis_data['Total']>0])
    for i in range(0,len(x)):
        mean = df[x[i]].mean()
        median = df[x[i]].median()
        std = df[x[i]].std()
        if std >10:
            df[x[i]]=df[x[i]].fillna(median)
        else:
            df[x[i]]=df[x[i]].fillna(mean)

In [90]:
fill_mis(data_test_1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()


In [91]:
data_test_1.shape

(5000, 67)

In [92]:
df_x =data_test_1[data_test_1.select_dtypes(include=['float64']).columns]
x=df_x.columns
len(x)

67

In [121]:
from sklearn.ensemble import RandomForestClassifier
X_train=np.array(data.drop(columns='greatstone_rating'))
y_train=np.array(data['greatstone_rating'])
X_test=np.array(data_test_1)

In [122]:
X_test.shape

(5000, 67)

In [123]:
rfcl = RandomForestClassifier(n_estimators = 393,min_samples_split=2,min_samples_leaf=2,max_depth=80,bootstrap= False)
rfcl = rfcl.fit(X_train, y_train)

In [128]:
y_predict_test = rfcl.predict(X_test)

In [129]:
len(y_predict_test)

5000

In [130]:
result=pd.DataFrame()
result['fund_id']=data_test['fund_id']
result['greatstone_rating']=y_predict_test

In [131]:
result.to_csv('result3.csv',index=False)